create campaign function integration with frontend
Akashic-fund/akashic pull request #4
Opened 2024-12-16 14:07 UTC by 0xshikhar

2024-12-16 14:54 UTC, positonic requested changes
I've left some feedback on the PR look forward to your responses

2024-12-16 14:54 UTC, positonic commented on .eslintrc.json
> +    "no-unused-vars": "warn",
Why are we not rather keeping the code clean than disabling best practices?

2024-12-16 14:54 UTC, positonic commented on components/create-campaign.tsx
> +    const identifierHash = keccak256(
Why do we need to create our own identifier? Doesn't CCP create one for us?

2024-12-16 14:54 UTC, positonic commented on components/create-campaign.tsx
> +    const campaignData1 = [
This needs a better variable name

2024-12-16 14:54 UTC, positonic commented on components/create-campaign.tsx
> +          identifierHash,
I see we are sending a unique Id to CCP. I imagine this should be our unique Akashic identifier?

2024-12-16 14:54 UTC, positonic commented on lib/test.js
> +// function createCampaign(bytes32 platformBytes) internal {
Can we rather stash this and commit it when we're ready?

2024-12-16 15:05 UTC, 0xshikhar commented on .eslintrc.json
> +    "no-unused-vars": "warn",
yes, we are following them - here instead of error, just converted them into warnings"

2024-12-18 13:06 UTC, positonic requested changes

2024-12-18 13:06 UTC, positonic commented on .eslintrc.json
> +    "no-unused-vars": "warn",
Let's keep them as errors. Prefer to comment out the code if necessary, but we should be deleting such code IMO.

2024-12-18 13:28 UTC, merged